### ISSUE TITLE
Client/Server connection

### ISSUE THREAD

**Issue by olemid** [frozenmistadventure/fmetp_tutorial_hololens2_stream#1]
Hi, thank you for this repo and support for Hololens 2. I built this with default settings to my Hololens, and it runs as it should and displays the camera. However when I start the PC scene, I can not make the Hololens client connect to the server.
I have made sure that the PC and Hololens are on the same network, though that might not be necessary. 
Running on Unity 2021.3.4f1 and FMETP Stream 3.168.

I'm sure there's just something I'm missing, I just don't know what.

**Comment by frozenmistadventure** [comment]
@olemid In general, it's due to firewall, you may turn off your PC's firewall and network discovery feature in your computer system settings.
related page: https://frozenmist.com/docs/apis/fmetp-stream/troubleshooting/

**Comment by frozenmistadventure** [comment]
> Hi, thank you for this repo and support for Hololens 2. I built this with default settings to my Hololens, and it runs as it should and displays the camera. However when I start the PC scene, I can not make the Hololens client connect to the server. I have made sure that the PC and Hololens are on the same network, though that might not be necessary. Running on Unity 2021.3.4f1 and FMETP Stream 3.168.
> 
> I'm sure there's just something I'm missing, I just don't know what.

@olemid In general, it's due to firewall, you may turn off your PC's firewall and network discovery feature in your computer system settings.
related page: https://frozenmist.com/docs/apis/fmetp-stream/troubleshooting/

**Comment by olemid** [comment]
Thank you very much, I didn't find this page earlier. I will have a look with our network admin as well.

**Comment by olemid** [comment]
Hello again. I changed my network setup, and it did connect as it should. The only thing I had to change was the OnTextureReceived event on the server's GameViewDecoder, since the reference in that event was missing. Now I have it up and running and it's looking great :) Thanks a lot!
